### PR TITLE
fix: move metadata to trace level context

### PR DESCRIPTION
**Pull request by nilslice**
Tested that the metadata is in the JSON output, but not against the Agent.

### CODE REVIEW

**Review by bhelx — APPROVED** [review]
Looks correct but i have not had a chance to test

**Comment by nilslice** [comment]
This reminds me, we can set up preview branches for Northflank deploys.

**Comment by bhelx** [comment]
> This reminds me, we can set up preview branches for Northflank deploys.

We could perhaps have a staging environment that we could push to to test. I don't think we can spin up a whole environment per branch though if that is what is meant.

**Comment by nilslice** [comment]
I do mean that and unless we have something that precludes us from it, they just asked me if we've ever used it haha so I'm pretty sure we can!

**Comment by nilslice** [comment]
@wikiwong i'm gonna merge this, so we can test it in the Node service. we'll need to rebase the other changes from it in your branch tho just a heads up

**Pull request merged**
