### PR TITLE
feat(observe api): seperate c++ bindings from c bindings

### PR DESCRIPTION
**Pull request by G4Vi**
This allows using the c++ bindings without the c bindings. Making the C++ bindings easier to use also a single header library. In a C++ project both bindings still may be used all the time.

### CODE REVIEW

**Comment by nilslice** [comment]
Should we move the component stuff out of here now that we've provided it to the community in wasi-observe? Seems like its fallen behind tooling and causing CI to fail.

**Comment by G4Vi** [comment]
> Should we move the component stuff out of here now that we've provided it to the community in wasi-observe? Seems like its fallen behind tooling and causing CI to fail.

I'd be happy to nuke the observe component support as I don't think anyone uses it and fixing it up, is probably just as much work as readding it, as I'm sure there's been tooling changes. If we have a need for it or someone contributes it, we could always readd it. @chrisdickinson What do you think?

**Comment by chrisdickinson** [comment]
Yeah, probably worth ripping that out for now. Git will remember it for us if we ever need it in the future!

**Review by nilslice — APPROVED** [review]
LGTM, assuming CI passes! Thanks for fixing up the wasmtime dependencies on the services. Nice to have this all green again.

**Pull request merged**
